import os 

ROOT_DIR = os.getcwd()
FILES_DIR = os.path.join(ROOT_DIR, 'files')
WINDOW_ICON_PATH = os.path.join(FILES_DIR, 'logo.jpg')

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'
